### ISSUE TITLE
Are the WSIs also publicly available?

### ISSUE THREAD

**Issue by guillaumejaume** [PangeaResearch/enlight-deeppt-data#1]
Hi, 

Congrats for curating such a rich cohort! I was wondering if the slides associated with the response are publicly available? Thanks!

**Comment by galdinstag** [comment]
Thanks!
The Yale dataset (Trastuzumab 2) is available at: https://wiki.cancerimagingarchive.net/pages/viewpage.action?pageId=119702524
For the Trastuzumab 1 dataset, some data is available at https://www.nature.com/articles/s41586-021-04278-5, as far as i know the H&E slides were not published
For the rest of the datasets, slides were not public due to 3rd party regulations.
Hope this helps.
Gal
